-- Crear base de datos dbCursos
CREATE DATABASE IF NOT EXISTS dbCurso
DEFAULT CHARACTER SET utf8;

-- Poner en uso
USE dbCurso;

-- Crear tabla PERSONAS
CREATE TABLE PERSONA
(
     DNIPER CHAR(8),
     NOMPER VARCHAR(50) NOT NULL,
     APEPER VARCHAR(80) NOT NULL,
     FECNAPER DATE NOT NULL,
     CELPER CHAR(9),
     EMAPER VARCHAR(100),
     SEXPER CHAR(1) NOT NULL,
     TIPPER CHAR(3) NOT NULL,
     DISTPER VARCHAR(80) NOT NULL,
     FECREGPER TIMESTAMP,
     PWSPER VARCHAR(20),
     CONSTRAINT  DNIPER_PK PRIMARY KEY (DNIPER)
     
); 

--
CREATE TABLE EMPLEADO
(
     IDEMP INT,
     DNIPER CHAR(8),
     FECINGEMP DATE NOT NULL,
     CARGEMP VARCHAR(40) NOT NULL,
     SALEMP DECIMAL(6,2) NOT NULL,
     IDDEP INT,
     ESTEMP CHAR(1),
     CONSTRAINT  IDEMP_PK PRIMARY KEY (IDEMP)
); 

CREATE TABLE DEPARTAMENTO
(
     IDDEP INT,
     NOMPED VARCHAR(50) NOT NULL,
     DNIPER CHAR(8),
     SALJEFDEP DECIMAL(8,2),
     CONSTRAINT  IDDEP_PK PRIMARY KEY (IDDEP)     
); 

CREATE TABLE CURSO
(
     CODCUR INT,
     DESCUR VARCHAR(50) NOT NULL,
     CATCUR CHAR(3) NOT NULL,
     DURCUR INT NOT NULL,
     CONSTRAINT  CODCUR_PK PRIMARY KEY (CODCUR)     
); 

CREATE TABLE OFERTA
(
     IDOFER INT,
     CODCUR VARCHAR(50),
     FECOFER CHAR(3) NOT NULL,
     FECINICCUROFER INT NOT NULL,
     IDEMP INT,
     CONSTRAINT  IDOFER_PK PRIMARY KEY (IDOFER)     
); 

CREATE TABLE INSCRIPCION
(
     IDINSC INT,
     DNIPER CHAR(8),
     IDEMP INT,
     IDOFER INT,
	 FECINS DATE NOT NULL,
     EVALINSC INT,
     CONSTRAINT  IDINSC_PK PRIMARY KEY (IDINSC)     
); 

CREATE TABLE HISTORICO
(
     IDHIS INT,
     DNIPER CHAR(8),
     FECFINHIST DATE NOT NULL,
     TIPHIS CHAR(3) NOT NULL,
	 COMEHIST VARCHAR(100),
     CONSTRAINT  IDHIS_PK PRIMARY KEY (IDHIS)     
); 


-- Relacionar la tabla PERSONA CON DEPARTAMENTO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);